### ISSUE TITLE
[Request] Request to Publish Repository as Public Docker Image

### ISSUE THREAD

**Issue by Obed0101** [cookieY/lobe-chat#1]
### 🥰 Feature Description

Hi Cookiey,

I hope you’re doing well. I wanted to ask if you could please upload the repository as a public Docker image. I need to use the custom embedding feature and am planning to explore free alternatives to OpenAI, possibly Groq or Google Text Embedding 004. Unfortunately, the pull request to the main branch might take a while.

### 🧐 Proposed Solution

Thank you so much for your help!

**Comment by Obed0101** [comment]
嗨，Cookiey、

希望你一切都好。我想问一下，能否请您将软件源作为公开的 Docker 镜像上传。我需要使用自定义嵌入功能，并计划探索 OpenAI 的免费替代方案，可能是 Groq 或 Google Text Embedding 004。不幸的是，向主分支提交拉取请求可能需要一段时间。

**Comment by cookieY** [comment]
yeelabs/lobe-chat-databases:v1.21.16
